= Getting started
:description: A description of the steps needed to get BICI up and running.

Bonita Intelligent Continuous Improvement (BICI) configuration instructions.

See https://documentation.bonitasoft.com/bici for more information.

See xref:_anchor[wrong anchor]

== Configure

=== Configure Profiles

You need to set up the Bonita Portal profile mapping for the profile `Configuration` and make sure Operations Managers are mapped to the provided profile `Process Manager`.
Moreover, for each process supervised by Operation Managers, the `Process Manager mapping` must also include the Operations Managers in order to display data of the processes in the `Operations Management` Living Application.

=== Synchronize data

In the xref:configure.adoc[Configure Living application]'s `Polling Status` tab, activate the synchronization to push your data into the BICI storage.

=== Configure processes

In the xref:configure.adoc[Configure Living application]'s `Configuration` tab, set target durations and create models for your processes.

== Explore

=== Monitor executing cases

Check out the xref:monitoring.adoc[Operation manager Living application]'s `Monitoring` tab, it contains live monitoring of executing cases.

=== Analyse performance of completed cases

Check out the xref:monitoring.adoc[Operation manager Living application]'s `Analytics` tab, it contains analytics of completed cases.
