name: Build PR preview

on:
  pull_request:
    # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # surge-preview write PR comments
    steps:
      - name: Build and publish PR preview
        # TMP use the branch of https://github.com/bonitasoft/bonita-documentation-site/pull/596
        uses: bonitasoft/bonita-documentation-site/.github/actions/build-and-publish-pr-preview/@feat/add_fail_on_warning_options
        with:
          # TMP use the branch of https://github.com/bonitasoft/bonita-documentation-site/pull/596
          doc-site-branch: feat/add_fail_on_warning_options
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          component-name: labs
          fail-on-warning: true
