name: Build PR preview

on:
  pull_request:
    branches:
      - master
    paths:
      - 'modules/ROOT/**'
      - 'antora.yml'
      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    env:
#      BRANCH_NAME: "${GITHUB_REF#refs/heads/}"
      COMPONENT_NAME: bici
    steps:
      - name: Echo environment variables
          # echo "commit_message=deploy ${{ github.sha }}" >> $GITHUB_ENV
        run: |
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/})
          PR_NUMBER=$(echo ${GITHUB_REF#refs/heads/})
          echo "BRANCH_NAME: ${BRANCH_NAME}"
          echo "COMPONENT_NAME: ${COMPONENT_NAME}"
          echo "PR_NUMBER: ${PR_NUMBER}"
      - name: Get documenation site source code
        run: |
          pwd
          ls -lha
          rm -rf *
          #TODO --depth 1 to optimize
          git clone https://github.com/bonitasoft/bonitasoft.github.io.git .
          #git branch -a
          #git fetch origin feat/build_single_component_branch_for_doc_content_pr_preview
          git branch -a
          git checkout feat/build_single_component_branch_for_doc_content_pr_preview
      - name: Temp npm install # TODO should be done by the repo script
        run: |
          node --version
          npm --version
          npm ci
      - name: Generate the site preview
        run: |
          ./build-preview.bash --branch ${GITHUB_HEAD_REF#refs/heads/} --component ${COMPONENT_NAME} --pr 12
          ls -lh build/site
        # pr number: see https://github.com/actions/checkout/issues/58
        #branch https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
#        run: ./build-preview.bash --branch ${{github.head_ref}} --component ${{env.COMPONENT_NAME}} --pr ${{}}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation-preview-${{env.COMPONENT_NAME}}-${{github.sha}}
          path: build/site
          if-no-files-found: error
      - name: Publish preview
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_DOC }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build/site
          build: |
            echo "fake build"
