name: Build PR preview

on:
  pull_request:
    paths:
      - 'modules/ROOT/**'
      - 'antora.yml'
      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    env:
      COMPONENT_NAME: bici
      # Except if you want to test in progress work that your content depends on, keep it set to master
      DOC_SITE_BRANCH: feat/build_single_component_branch_for_doc_content_pr_preview
    steps:
      - name: Get documenation site source code
        run: |
          pwd
          ls -lha
          # Remove existing .git directory
          rm -rf *
          #TODO --depth 1 to optimize
          git clone https://github.com/bonitasoft/bonitasoft.github.io.git .
          git checkout ${DOC_SITE_BRANCH}
      - name: Compute environment variables
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
          echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV
          echo "mini_name=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
      # TODO pass the site-url argument https://{{repository.owner}}-{{repository.name}}-{{job.name}}-pr-{{pr.number}}.surge.sh.
      - name: Publish preview
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_DOC }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build/site
          failOnError: true
          build: |
            ./build-preview.bash --branch "${{ env.BRANCH_NAME }}" --component "${{ env.COMPONENT_NAME }}" --pr "${{ env.PR_NUMBER }}"
            ls -lh build/site
