name: Contribution checks

on:
  pull_request:

jobs:
  check_antora_content_guidelines:
    permissions:
      pull-requests: write # "pr-antora-content-guidelines-checker" write PR comments when the PR doesn't match the "Guidelines"
    # TODO use master when https://github.com/bonitasoft/bonita-documentation-site/pull/642 is merged
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml@ci/add_reusable_workflow_antora_contrib_checks_guide
