name: Contribution checks

on:
  pull_request:
jobs:
  check_contribution:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # "pr-antora-content-guidelines-checker" write PR comments
    steps:
      - name: Check PR content
        uses: bonitasoft/actions/packages/pr-antora-content-guidelines-checker@v2
        with:
          attributes-to-check: ':description:,:page-aliases:'
          files-to-check: 'adoc'
          forbidden-pattern-to-check: 'https://documentation.bonitasoft.com, link:https, link:http, link:, xref:https, xref:http, xref:_, xref:#'